### ISSUE TITLE
publish 0.4.3?

### ISSUE THREAD

**Issue by Pomax** [cfpb/wagtail-inventory#14]
https://github.com/cfpb/wagtail-inventory/pull/11 landing is a pretty important improvement, and having a 0.4.3 available with those changes means a Pipfile.lock can point to that, rather than having to point to a master branch on git (which has been the source of some bug reports for pipenv... it doesn't seem to always work for everyone =S)

**Comment by chosak** [comment]
@Pomax thanks for the encouragement! This change is released in new [version 0.5](https://github.com/cfpb/wagtail-inventory/releases/tag/0.5).
