### ISSUE TITLE
Could we get a "--no-input" flag for the "manage block-inventory" command?

### ISSUE THREAD

**Issue by Pomax** [cfpb/wagtail-inventory#15]
Right now the `manage block_inventory` command can lead to user prompts, where someone has to manually type "y" and hit enter, which makes it very hard to use in automated deployment, since there is no "user" available to type anything in that context.

A number of `manage` commands support the `--no-input` flag which automates the question and answer process, simply assuming the answer is supposed to be "yes" to every question, so that deployment scripts can add that flag wherever users would normally be prompted for confirmation, and it would be _super_ useful to have that available for the inventory plugin command, too =)

**Comment by chosak** [comment]
@Pomax thanks for opening this. I see [this comment](https://github.com/mozilla/foundation.mozilla.org/pull/1640#issuecomment-406685861) over on your repo -- is your issue just that you want this flag to be supported for consistency, or have you actually encountered cases where input is required? I can't think of any steps that would ask for input; can you provide specific examples of where you see user prompts?

A PR to add the flag would be welcomed! 😄

**Comment by Pomax** [comment]
we can't automatically deploy if there is no flag that does what the `--no-input` flag allows, since we already have a wagtail instance up, it has loads of pages and blocks, and `manage block_inventory` during bootstrap will guaranteed hit something that it wants a human to type "yes" for =)

I can try to make a PR, but I'm a JS dev who dabbles in python and when we're talking this deep down into Django, I'm pretty sure you know way more about this than I do =(

**Comment by chosak** [comment]
@Pomax thanks for the reply. I don't know of any logic in `block_inventory` that would require human input. So even if we were to add the flag, it's not clear what logic it should be hooked up to.

You can see the logic for the command [here](https://github.com/cfpb/wagtail-inventory/blob/master/wagtailinventory/management/commands/block_inventory.py#L14); it's fairly straightforward. First it deletes all of the existing blocks (which requires no user input; it's just a database delete) and then iterates over all pages and blocks to create new inventory (also shouldn't require any user input).

Have you seen examples where user input is required?

**Comment by Pomax** [comment]
I see. That's very curious, I could have sworn I was getting y/n questions but I can't reproduce those now O_o

**Comment by chosak** [comment]
Thanks for double-checking @Pomax. Please report if you encounter any other issues along these lines. Closing this issue for now.
