### ISSUE TITLE
wagtail 2.1+ support?

### ISSUE THREAD

**Issue by Pomax** [cfpb/wagtail-inventory#17]
It looks like wagtail-inventory is blocking upgrading to django 2.1 with wagtail 2.3/2.4, are there any true problems or is this simply a matter of updating the version requirements and publishing a 0.5.2 with those updated requirements?

**Comment by chosak** [comment]
Thanks for the reminder, @Pomax, I'll check out those versions.

**Comment by Pomax** [comment]
I've thrown up a PR that just bumps the version requirements, though I didn't run extensive testing for it =)

**Comment by Pomax** [comment]
Hi @chosak, any possibility of landing the PR? we've been testing it on our mozilla foundation repo and it doesn't look like anything's breaking.

**Comment by chosak** [comment]
@Pomax support for Django 2.1 and Wagtail 2.3/2.4 is now available in [wagtail-inventory 0.6](https://pypi.org/project/wagtail-inventory/0.6/). Thank you as always for your usage and encouragement of this package.
