### ISSUE TITLE
Wagtail 2.5 Support

### ISSUE THREAD

**Issue by cadecairos** [cfpb/wagtail-inventory#20]
Hello, [Wagtail 2.5 is out](https://docs.wagtail.io/en/v2.5/releases/2.5.html). Can we get an update to support it? As it stands, Pipenv can not generate a lockfile because wagtail-inventory requires [`wagtail<2.5`](https://github.com/cfpb/wagtail-inventory/blob/master/setup.py#L7)

**Comment by Pomax** [comment]
Hm, I spun up a custom copy over on https://github.com/Pomax/wagtail-inventory/blob/master/setup.py with our Pipfile updated to:
```
...
Django = "==2.2"
...
wagtail = "==2.5"
wagtail-factories = "*"
wagtail-inventory = {git = "https://github.com/Pomax/wagtail-inventory"}
...
```

But weirdly despite installing fine, and "running" fine, wagtail still says it's at 2.4 instead of 2.5

Checked the lockfile, but that very clearly says it has 2.5 installed:
```
        "wagtail": {
            "hashes": [
                "sha256:0b1357bc66873d1c3403791e717a15c8b01d3d0e67083fe5f9eff60d7f7d9d77",
                "sha256:19de8dd6390429c1c6e921487e997a64fa9334da0c6255f1e9988d30729fce1a"
            ],
            "index": "pypi",
            "version": "==2.5"
        },

```

**Comment by chosak** [comment]
@cadecairos @Pomax thanks very much for highlighting this and, as always, for your support for this project.

I've pushed a release candidate ([wagtail-inventory==0.7rc1](https://pypi.org/project/wagtail-inventory/0.7rc1/)) that should work with the latest versions. Unfortunately I don't have a Wagtail site on 2.5 to test this against right now. Would you mind giving it a try on your site?

**Comment by Pomax** [comment]
absolutely, we'll report back!

**Comment by Pomax** [comment]
@chosak looks like https://github.com/cfpb/wagtail-inventory/blob/0.7rc1/setup.py#L7 still needs updating to include, rather than exclude Django 2.2 and Wagtail 2.5?

**Comment by chosak** [comment]
@Pomax thank you! That's an obvious thing I should have caught. I'm glad I went the release candidate route. I've uploaded [wagtail-inventory==0.7rc2](https://pypi.org/project/wagtail-inventory/0.7rc2/) that fixes that.

**Comment by Pomax** [comment]
haha, rc all the things!

**Comment by Pomax** [comment]
A test with Django 2.2.1, Wagtail 2.5 and the 0.7rc2 looks good to me! No pipenv install errors, and running wagtail uses 2.5 with the block inventory settings menu still there, and finding all the relevant pages for specific blocks \o/

**Comment by chosak** [comment]
Thanks @Pomax. Version 0.7 is [on PyPI](https://pypi.org/project/wagtail-inventory/) now.

**Comment by Pomax** [comment]
awesome, thanks so much for the help!
