### ISSUE TITLE
Address pagination changes in Wagtail 2.5+

### ISSUE THREAD

**Issue by juan0tron** [cfpb/wagtail-inventory#22]
My current setup:

Wagtail 2.6.2
Django 2.2.6
wagtail-inventory 0.7

All manage.py functions display the following warning in the console:

```
/lib/python3.6/site-packages/wagtail/utils/pagination.py:10: RemovedInWagtail27Warning: wagtail.utils.pagination is deprecated. Use django.core.paginator.Paginator directly with get_page instead category=RemovedInWagtail27Warning)
```

This is most likely due to a change to Wagtail's pagination handling - the fix for this is detailed in the [Wagtail 2.5 release notes](https://docs.wagtail.io/en/v2.6.3/releases/2.5.html#changes-to-admin-pagination-helpers). This change should be applied under [/wagtailinventory/views.py](https://github.com/cfpb/wagtail-inventory/blob/master/wagtailinventory/views.py).

As per Wagtail's [depreciation policy](https://docs.wagtail.io/en/v2.6.3/releases/upgrading.html#deprecation-policy), this change will be necessary for this package to be compatible with Wagtail 2.7.

**Comment by chosak** [comment]
@juan0tron thanks for opening this issue! I've opened #23 to use Django's pagination in Wagtail 2.5+. If you get a chance, would you mind giving the version at that PR a try?
