### ISSUE TITLE
publish to pypi?

### ISSUE THREAD

**Issue by Pomax** [cfpb/wagtail-inventory#24]
Hiya,

it looks like some code landed about 2 weeks ago that solves a potential security issue for anyone using wagtail-inventory, would it be possible to get the new version published to PyPi so that folks can safely update rather than linking directly to a git commit in their pip requirements?

**Comment by chosak** [comment]
Hi @Pomax, are you referring to the changes in #23, or something else? Can you share more information about why this would be a security issue? (via my GH profile email if you prefer)

I'll get a new release out with those changes -- thanks for the prompt.

**Comment by Pomax** [comment]
It's an indirect security issue: there's a problem with a popular django library that no longer exists as of wagtail 2.6, so in order to update to that, people need a version of wagtail-inventory that has https://github.com/cfpb/wagtail-inventory/pull/23 landed in =)

**Comment by chosak** [comment]
@Pomax version 0.8 [is on PyPI](https://pypi.org/project/wagtail-inventory/). Please let us know if you run into any issues with it!

**Comment by Pomax** [comment]
awseome, thanks so much!
