### ISSUE TITLE
Remove wagtail max version in setup.py

### ISSUE THREAD

**Issue by m3brown** [cfpb/wagtail-inventory#37]
Following up on a conversation in #36, I suggest the team consider removing the max supported version of Wagtail in the setup.py

## Current behavior

When installing libraries into a python environment (using pip, pipenv, etc.), wagtail-inventory restricts the permitted versions of Wagtail with a minimum version (currently 2.7, inclusive) and a maximum version (currently 2.12, exclusive).

This means that when the next version of wagtail comes out (e.g. 2.12.0), projects that use wagtail-inventory will not be able to upgrade until wagtail-inventory releases an update to its setup.py max version.

This gives 2 potential routes for a project owner:
1) Remove wagtail-inventory from the project until an update is released
2) Wait to update wagtail, which assumes CFPB will maintain wagtail-inventory indefinitely and timely.

## Expected behavior

Each project should have the freedom to pair wagtail-inventory with a new version of wagtail, even if CFPB has yet to test the new version.

This aligns with guidance in [python.org documentation](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires)

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

Some workaround ideas:

*  You can define your supported versions in the README and in the tox config. Of course, this is not programmatically enforced, but that's kind of my point from the perspective of the external community.
*  Consider rephrasing the [development standards](https://github.com/cfpb/development/blob/main/standards/python.md#specifying-dependencies-in-requirementstxt-or-setuppy) to clarify that "unsupported versions" refers to known incompatibilities, but does not apply to untested future versions.

**Comment by m3brown** [comment]
The intent of this issue (near term, at least) is resolved by #38, where the maximum version was set to `<3`.

The blockage will appear again when Wagtail reaches V3.0.0, and I'm hopeful the CFPB team is still actively maintaining this project when that day arrives!

**Comment by Scotchester** [comment]
Just noticed this issue was still open.

> The blockage will appear again when Wagtail reaches V3.0.0, and I'm hopeful the CFPB team is still actively maintaining this project when that day arrives!

I think we are probably too conservative to assume that wagtail-inventory will keep working with the next major version of Wagtail, and I'm pretty confident that we'll still be maintaining it, so I will close this for now :)

**Comment by willbarton** [comment]
Well, and if not, I wouldn't want to assume the current code would work out-of-the-box anyway.
