### ISSUE TITLE
Select dialogs in inventory form are missing chevron icon

### ISSUE THREAD

**Issue by m3brown** [cfpb/wagtail-inventory#39]
Short description explaining the high-level reason for the new issue.

## Current behavior

In the wagtail inventory page, there are 6 select elements that have no visual cue indicating that they are select dialogs. The UI would suggest they are text boxes. When clicked, the dropdown appears and functionality works as expected.

## Expected behavior

The UI of the select dialog should have some sort of visual element indicating that the field is a dropdown. The easy solution is to leverage wagtail's built in CSS styles to render a chevron icon on the right hand side.

## Steps to replicate behavior (include URLs)

1. Go to the wagtail inventory page (http://localhost:8000/admin/inventory/)
2. Observe the UI of the 6 select elements at the top of the page

## Screenshots

![image](https://user-images.githubusercontent.com/2699164/104196314-a24b4e00-53f1-11eb-9f5b-4811b642de89.png)

**Comment by chosak** [comment]
@m3brown thanks for reporting this and for opening a PR! This would be a nice improvement. I was curious if we could do this by leveraging the built-in Wagtail admin input template instead of writing our own; would the approach in #42 work for you?

**Comment by chosak** [comment]
Fixed in #42.
