### ISSUE TITLE
There are No Permissions policies available!

### ISSUE THREAD

**Issue by hazho** [cfpb/wagtail-inventory#47]
## Current behavior
the Inventory is shown to all users, there are no restrictions

## Expected behavior
it has to be given at least the BASIC PERMISSIONS, to prevent certain groups of users from viewing and searching across the entire DB, basically this should be available for the SUsers only, unless the complex permissions policies provided(perhups in the future)..!

**Comment by chosak** [comment]
@hazho thank you again for this, and apologies for the long delay in getting back to this issue. [Release 2.0.0](https://github.com/cfpb/wagtail-inventory/releases/tag/2.0.0) of this package converted the block inventory to a Wagtail report and made it available only to admin users.

#77 that I've just opened adds the ability to enable/disable this per user group using Wagtail's permissions framework.
