### ISSUE TITLE
setup requires specific version of tqdm

### ISSUE THREAD

**Issue by easherma-truth** [cfpb/wagtail-inventory#52]
https://github.com/cfpb/wagtail-inventory/blob/8b57fb3ebee8a1386fe9ec92a164cc54e31a4238/setup.py#L5

We've got a newer version than this installed in our env, is it possible to expand it to range of expected versions?

**Comment by chosak** [comment]
@easherma-truth's fix from #53 is now merged and released to PyPI in release [1.4.1](https://pypi.org/project/wagtail-inventory/1.4.1/) as well as a [1.3.1](https://pypi.org/project/wagtail-inventory/1.3.1/) for users who are not yet on the 2.15 version of Wagtail, which is required as of 1.4 of this project.

**Comment by easherma-truth** [comment]
Thanks so much @chosak ! This library really helped us confirm the extent of a potential bug the other morning, so much thanks all around! :-D
