### ISSUE TITLE
Wagtail 3 compatibility

### ISSUE THREAD

**Issue by nickmoreton** [cfpb/wagtail-inventory#59]
The package can be updated to work with Wagtail 3

## Current behavior

The package has a version constraint for Wagtail of "wagtail>=2.15,<3"

## Expected behavior

Be able to install the package when using Wagtail 3+

## Steps to replicate behavior (include URLs)

Installing the package (I was using poetry) fails

## Solution

I have submitted a pull request to upgrade the package. https://github.com/cfpb/wagtail-inventory/pull/58

**Comment by chosak** [comment]
Implemented in #63 and released in [version 1.6](https://pypi.org/project/wagtail-inventory/1.6/).
