### ISSUE TITLE
Please create a release for Wagtail 5

### ISSUE THREAD

**Issue by cnk** [cfpb/wagtail-inventory#72]
I just installed commit [c331865](https://github.com/cfpb/wagtail-inventory/commit/c3318650a5f593ab88f0c771f4e636b0b66e6c94) into a project that is running Wagtail 5.0rc1. Everything is working as expected. I would love to see a pypi release so I can use that rather than a github url in my requirements file.

**Comment by chosak** [comment]
Hi @cnk - this project [doesn't pin an upper bound](https://github.com/cfpb/wagtail-inventory/blob/c3318650a5f593ab88f0c771f4e636b0b66e6c94/pyproject.toml#L13) to the Wagtail version (`wagtail>=4.0`) and so it should be possible to install with the 5.0 RC. We typically don't make PyPI releases of our packages to support Wagtail RC versions.

I just tried a new project with `pip install wagtail==5.0rc1 wagtail-inventory`, and the same combination works when in a requirements.txt file. Are you running into an error when you try this combination?

**Comment by cnk** [comment]
No the package worked flawlessly. I was just hoping for a new release so I could install the report-ified version from PyPi instead of a GitHub url.

**Comment by chosak** [comment]
> the report-ified version from PyPi

Do you mean the new report interface released in [version 2.0](https://github.com/cfpb/wagtail-inventory/releases/tag/2.0.0)? That version [is available on PyPI](https://pypi.org/project/wagtail-inventory/).

**Comment by cnk** [comment]
Sorry. I don't know how I missed seeing the 2.0 release.

**Comment by chosak** [comment]
No worries, @cnk, thanks for using this package!
