### ISSUE TITLE
"Page block" in the group edit form?

### ISSUE THREAD

**Issue by cnk** [cfpb/wagtail-inventory#79]
Does everyone else see "Page block" in their group edit form? The docs say

`Other user groups may be granted access to the report by giving them the "Can view" "Page block" permission in Wagtail Group settings.`

But I don't see "Page block" in the "Object permissions" section of my group editing pages e.g. https://xyz.localhost/admin/groups/2078/ In fact I don't see the word "block" on that page at all. The report is working just fine once I assign the permission via the database and [the hook for putting the permissions on the group admin form](https://github.com/cfpb/wagtail-inventory/blob/main/wagtailinventory/wagtail_hooks.py#L33) looks OK to me so I thought I would start by asking if it was just me.

I am using Wagtail 5.1.2, Django 3.2, and wagtail-inventory 2.0.0.

**Comment by chosak** [comment]
Hi @cnk! This functionality was just added recently in #77 in [release 2.3](https://github.com/cfpb/wagtail-inventory/releases/tag/2.3). Are you able to update your wagtail-inventory version?

**Comment by cnk** [comment]
D'oh! Upgrading fixed it. I should have checked if I was running the latest.
