### ISSUE TITLE
Comptability with Wagtail 2?

### ISSUE THREAD

**Issue by alanmoo** [cfpb/wagtail-inventory#8]
Hi @chosak, any plans to make this compatible with Wagtail 2? Or any guidance on what might need updating in order to submit a PR for Wagtail 2 compatibility?

**Comment by chosak** [comment]
Hi @alanmoo, thanks very much for opening this issue. Encouragement like this helps motivate us to add that support. We have [a similar open issue](https://github.com/cfpb/wagtail-sharing/issues/22) on one of our other projects, [wagtail-sharing](https://github.com/cfpb/wagtail-sharing).

I'll take a look and see what might be involved in adding support here.

**Comment by alanmoo** [comment]
It looks like https://github.com/cfpb/wagtail-sharing/issues/22 has been addressed, is it likely that this project just needs a [similar treatment](https://github.com/cfpb/wagtail-sharing/pull/24)?
